export const hotelTypes = [
  "Budget",
  "Bontique",
  "Luxury",
  "Family",
  "Romantic",
  "Ski Resort",
  "Hiking Resort",
  "Beach Resort",
  "Golf Resort",
  "Adventure Resort",
  "Business",
  "Cabin",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
];

export const hotelFacilities = [
  "WiFi",
  "Parking",
  "Outdoor Pool",
  "Fitness Center",
  "Pets Allowed",
  "Toiletries",
  "Laundry",
  "AC",
  "Fridge",
  "TV",
  "Microwave",
  "Self check-in",
];
